apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-resource-service-properties
data:
  application.properties: |
    management.endpoint.health.probes.enabled=true
    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672
    spring.rabbitmq.username=bladesv
    spring.rabbitmq.password=root
    spring.rabbitmq.template.exchange=id-resource
    spring.rabbitmq.template.routing-key=id-resource-key
    spring.rabbitmq.template.retry.max-attempts=3
    spring.rabbitmq.template.retry.enabled=true
    server.port=8080
    spring.datasource.password=pass
    spring.datasource.url=jdbc:postgresql://resource-database:5432/mp3resource
    spring.datasource.username=root
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.show-sql=true
    #spring.jpa.properties.hibernate=null
    spring.servlet.multipart.max-file-size=20MB
    spring.servlet.multipart.max-request-size=20MB
    user.aws.awsAccessKeyId=test
    user.aws.awsRegion=us-east-1
    user.aws.awsSecretAccessKey=test2;
    user.aws.s3.bucket.name=bladesv
    user.aws.s3Endpoint=http://localstack:4566/
    user.messaging.queue=id-resource-queue

  