apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-victoria-metrics
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: "song-store-metrics"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: [ "host.docker.internal:8080" ]
