apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-storage-service-properties
data:
  application.properties: |
    spring.application.name=storage-service
    spring.config.import=optional:configserver:http://config-server:8099
