apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-resource-processor-properties
data:
  application.properties: |
    spring.application.name=resource-processor
    spring.config.import=optional:configserver:http://config-server:8099
