apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-env-song-service
data:
  SONG_SERVICE_PORT: "8081"
  SONG_SERVICE_DB_HOST: "song-database"
  SONG_SERVICE_DB_PORT: "5432"
  SONG_SERVICE_DB_NAME: "songs"
  SONG_SERVICE_JPA_DDL_AUTO: "none"
  SPRING_PROFILES_ACTIVE: "k8s"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-env-localstack
data:
  DOCKER_HOST: "unix:///var/run/docker.sock"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test2"
  AWS_DEFAULT_REGION: "us-east-1"
  DEFAULT_REGION: "us-east-1"
  DEBUG: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-env-rabbitmq
data:
  RABBITMQ_DEFAULT_USER: "bladesv"
  RABBITMQ_DEFAULT_PASS: "root"


