apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-eureka-server-properties
data:
  application.properties: |
    spring.application.name=eureka-server
    spring.config.import=optional:configserver:http://config-server:8099
