{{ if not .Values.profile.local }}
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8099
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      name: config-server
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server-container
          image: config-server-image:latest
          livenessProbe:
            httpGet:
              port: 8099
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 5
          readinessProbe:
            httpGet:
              port: 8099
              path: /actuator/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 5
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          volumeMounts:
            - mountPath: /app/resources/application.properties
              name: config-server-app-properties
              subPath: application.properties
          ports:
            - containerPort: 8099
          imagePullPolicy: Never
      restartPolicy: Always
      volumes:
        - name: config-server-app-properties
          configMap:
            name: config-map-config-server-properties
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
{{ end }}
      