apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-env-song-service
data:
  SONG_SERVICE_PORT: "8081"
  SONG_SERVICE_DB_HOST: "song-database-service"
  SONG_SERVICE_DB_PORT: "5432"
  SONG_SERVICE_DB_NAME: "songs"
  SONG_SERVICE_JPA_DDL_AUTO: "none"
  SPRING_PROFILES_ACTIVE: "k8s"


