apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-env-localstack
data:
  DOCKER_HOST: "unix:///var/run/docker.sock"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test2"
  AWS_DEFAULT_REGION: "us-east-1"
  DEFAULT_REGION: "us-east-1"
  DEBUG: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-env-rabbitmq
data:
  RABBITMQ_DEFAULT_USER: "bladesv"
  RABBITMQ_DEFAULT_PASS: "root"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-env-kafka
data:
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper.default.svc.cluster.local:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"




