apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: port1
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: port2
  type: ClusterIP
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq"
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
              name: port1
            - containerPort: 15672
              name: port2
          envFrom:
            - configMapRef:
                name: config-map-env-rabbitmq
          imagePullPolicy: IfNotPresent
      restartPolicy: Always



