apiVersion: v1
kind: Service
metadata:
  name: song-service
spec:
  selector:
    app: song-service
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30081
      targetPort: 8081
  type: NodePort
  