apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
spec:
  selector:
    app: victoria-metrics
  ports:
    - protocol: TCP
      port: 8428
      targetPort: 8428
  type: {{ .Values.service.type }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoria-metrics
spec:
  serviceName: "victoria-metrics"
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics
          ports:
            - containerPort: 8428
          args:
            - "-promscrape.config=/etc/prometheus/prometheus.yml"
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: victoria-metrics-config
              subPath: prometheus.yml
            - mountPath: "/victoria-metrics-data"
              name: victoria-metrics-data
      volumes:
        - name: victoria-metrics-config
          configMap:
            name: config-map-victoria-metrics
        - name: victoria-metrics-data
          emptyDir: { }
