server:
  port: 8082
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: bladesv
    password: root

    template:
      exchange: id-resource
      routing-key: id-resource-key
      retry:
        max-attempts: 3
        enabled: true
management:
  endpoint:
    health:
      probes:
        enabled: true


user:
  messaging:
    queue: id-resource-queue
  resource-service: http://localhost:8081/resources/
  song-service: http://localhost:8083/songs
